version: '3'

services:
  mariadb:
    restart: always
    image: mariadb:latest
    volumes:
      - "./data:/var/lib/mysql/data"
      - "./conf:/etc/mysql/logs"
      - "/var/docker/mariadb/conf:/etc/mysql/conf.d"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "heticdb"
      MYSQL_USER: 'hetic'
      MYSQL_PASSWORD: 'hetic'

  phpmyadmin:
    image: phpmyadmin
    restart: always
    expose:
      - "40001"
    ports:
      - "40001:80"
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
      
  web:
    build: .
    command: python app.py
    ports:
      - "80:80"
    restart: always
        
